### ISSUE TITLE
可能由Name键值缺失导致的无法设置API的问题

### ISSUE THREAD

**Issue by Alexme9125** [Soulter/llms#6]
问题过程：在开发者修复依赖部署问题后，插件能正常地安装并加载。但在设置Google Gemini的API Key时出现了500错误，并报错，控制台中显示一个HTTP POST请求缺少name字段：
ERROR in app: Exception on request POST /api/plugin/update
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\quart\app.py", line 1403, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\quart\app.py", line 1441, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\quart\app.py", line 1029, in handle_user_exception
    raise error
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\quart\app.py", line 1439, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\quart\app.py", line 1535, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Bot\AstrBot\dashboard\routes\plugin.py", line 77, in update_plugin
    plugin_name = post_data["name"]
                  ~~~~~~~~~^^^^^^^^
KeyError: 'name'
<img width="313" alt="Screenshot 2024-10-11 at 12 39 23" src="https://github.com/user-attachments/assets/490976c6-c4dd-4f8f-b9d1-38cb3a72135d">

**Comment by Soulter** [comment]
原因出在前端引用了错误的api，已在 AstrBot 修复。可以在仪表盘右上角通过输入 commit hash 的方式更新。最新的 commit hash 为 `42d0a641e27dd38238402924fdd7dd94e72b62c0`
